#!/usr/bin/env python3
"""
Alert feed simulator.

Generates synthetic CAP 1.2 alerts and POSTs them to the bridge's
``/api/v1/compose`` endpoint at a configurable rate. Useful for end-to-end
testing of the dedup engine, circuit breaker, audit log, and downstream
routing without standing up real NOAA / NWS / USGS / IPAWS connections.

Usage (from repo root)::

    python etc/simulator.py --alerts 50 --interval 2

Or with a different target URL::

    python etc/simulator.py --alerts 10 --interval 5 \\
        --target https://bridge.example.com/api/v1/compose
"""
from __future__ import annotations

import argparse
import json
import logging
import random
import sys
import time
import uuid
from dataclasses import dataclass
from typing import Sequence

try:  # pragma: no cover — urllib is stdlib; keep the import obvious.
    import urllib.error
    import urllib.request
except ImportError as _e:  # pragma: no cover
    raise SystemExit(f"urllib unavailable: {_e}")

DEFAULT_TARGET = "http://localhost:8000/api/v1/compose"
DEFAULT_ALERTS = 25
DEFAULT_INTERVAL = 2.0

SEVERITIES = ("Extreme", "Severe", "Moderate", "Minor")
EVENTS = (
    "Tornado Warning",
    "Flash Flood Warning",
    "Wildfire Evacuation",
    "Earthquake Aftershock",
    "Severe Thunderstorm",
    "Coastal Flood Watch",
)
AREAS = (
    ["Los Angeles County, CA"],
    ["Harris County, TX"],
    ["Miami-Dade County, FL", "Broward County, FL"],
    ["King County, WA"],
    ["Cook County, IL"],
    ["Maricopa County, AZ"],
)


@dataclass
class SimResult:
    sent: int
    accepted: int
    deduplicated: int
    failed: int

    def __str__(self) -> str:  # pragma: no cover — formatting
        return (
            f"sent={self.sent} accepted={self.accepted} "
            f"deduplicated={self.deduplicated} failed={self.failed}"
        )


def _build_alert(idx: int) -> dict:
    severity = random.choice(SEVERITIES)
    return {
        "event_id": f"sim-{uuid.uuid4().hex[:12]}-{idx:04d}",
        "severity": severity,
        "headline": f"{random.choice(EVENTS)} — simulated alert {idx}",
        "description": (
            f"Synthetic alert generated by etc/simulator.py for end-to-end "
            f"testing of the cap-ipaws-bridge pipeline. Severity={severity}."
        ),
        "instruction": "This is a TEST. Take no action. Generated by etc/simulator.py.",
        "target_areas": random.choice(AREAS),
    }


def _post_one(target: str, alert: dict, timeout: float) -> tuple[int, str]:
    body = json.dumps(alert).encode("utf-8")
    req = urllib.request.Request(
        target,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", errors="replace")


def run(
    target: str = DEFAULT_TARGET,
    alerts: int = DEFAULT_ALERTS,
    interval: float = DEFAULT_INTERVAL,
    duplicate_rate: float = 0.0,
    timeout: float = 10.0,
    log: logging.Logger | None = None,
) -> SimResult:
    """Run the simulator loop synchronously and return a tally."""
    log = log or logging.getLogger(__name__)

    if alerts <= 0:
        raise ValueError("alerts must be > 0")
    if interval < 0:
        raise ValueError("interval must be >= 0")

    last_alert: dict | None = None
    tally = SimResult(sent=0, accepted=0, deduplicated=0, failed=0)

    for i in range(alerts):
        if last_alert is not None and random.random() < duplicate_rate:
            alert = last_alert
            log.info("[%d/%d] replaying %s (dedup probe)", i + 1, alerts, alert["event_id"])
        else:
            alert = _build_alert(i)
            log.info(
                "[%d/%d] %s severity=%s areas=%s",
                i + 1, alerts, alert["event_id"], alert["severity"],
                ",".join(alert["target_areas"]),
            )

        tally.sent += 1
        try:
            status, body = _post_one(target, alert, timeout)
        except (urllib.error.URLError, TimeoutError) as exc:
            log.warning("    transport error: %s", exc)
            tally.failed += 1
        else:
            lower = body.lower()
            if status == 200 and "deduplicated" in lower:
                tally.deduplicated += 1
            elif 200 <= status < 300:
                tally.accepted += 1
            else:
                log.warning("    HTTP %d: %s", status, body[:200])
                tally.failed += 1

        last_alert = alert
        if i + 1 < alerts and interval > 0:
            time.sleep(interval)

    return tally


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="etc/simulator.py",
        description="Simulate inbound CAP alerts against the bridge.",
    )
    p.add_argument("--alerts", type=int, default=DEFAULT_ALERTS, help="Number of alerts to send.")
    p.add_argument("--interval", type=float, default=DEFAULT_INTERVAL, help="Delay (seconds) between sends.")
    p.add_argument("--target", default=DEFAULT_TARGET, help="Compose endpoint URL.")
    p.add_argument(
        "--duplicate-rate",
        type=float,
        default=0.0,
        help="Probability (0..1) of resending the previous alert to probe dedup.",
    )
    p.add_argument("--timeout", type=float, default=10.0, help="Per-request timeout (seconds).")
    p.add_argument("--seed", type=int, help="Optional RNG seed for reproducible runs.")
    p.add_argument("--quiet", action="store_true", help="Only print the final tally.")
    return p.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(message)s",
    )
    if args.seed is not None:
        random.seed(args.seed)

    log = logging.getLogger("simulator")
    log.info("→ posting %d alerts to %s every %.2fs", args.alerts, args.target, args.interval)

    result = run(
        target=args.target,
        alerts=args.alerts,
        interval=args.interval,
        duplicate_rate=args.duplicate_rate,
        timeout=args.timeout,
        log=log,
    )
    print(result)
    return 0 if result.failed == 0 else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
